version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"  

  was:
    image: node:latest
    working_dir: /app
    volumes:
      - .was:/app
    ports:
      - "3000:3000"
    command: npm start

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_USER: your_postgres_user
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: your_database_name

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: your_rabbitmq_user
      RABBITMQ_DEFAULT_PASS: your_rabbitmq_password

  redis:
    image: redis:latest
    ports:
      - "6379:6379"